export const DataMap = [
  {
    id: 'Vladivostok',
    name: 'Владивосток',
  },
  {
    id: 'Voronezh',
    name: 'Воронеж',
    title: 'Центрально-Черноземный филиал',
    cityName: 'г. Воронеж',
    manager: 'Дровянникова Елена Гарриевна',
    position: 'Директор филиала',
    congratsText:
      '«Желаю СберЛизингу всегда быть ТОП-1 на рынке! Смотреть с уверенностью в завтрашний день, с удовольствием работать и отдыхать на полную катушку! С праздником!»',
    foundationYear: '2009',
    employeesNumber: '59',
    menWomen: ['53', '47'],
    clients: '2144',
    autosLight: '34,55%',
    autosCommercial: '13,76%',
    autosCargo: '27,62%',
    autosSpecial: '21,62%',
    buses: '0,63%',
    equipment: '1,82%',
    faceImg: '/img/popupImg/Voronezh/face.png',
    bgImg: '/img/popupImg/Voronezh/bg.svg',
  },
  {
    id: 'Rostov-on-Don',
    name: 'Ростов-на-Дону',
    title: 'Юго-Западный филиал',
    cityName: 'г. Ростов-на-Дону',
    manager: 'Ткаченко Надежда Леонидовна',
    position: 'Директор филиала',
    congratsText:
      '«Поздравляю всех с юбилеем нашей замечательной компании! Хочу пожелать СберЛизингу долгих лет стабильного успеха, уверенной деятельности, неугасаемого процветания. Пусть каждый год успешной работы выводит нашу компанию на более высокий уровень. Всем сотрудникам — здоровья и крепких сил, высокого профессионализма, счастья и благополучипя.И всем нам только довольных клиентов и масштабных проектов!»',
    foundationYear: '2010',
    employeesNumber: '82',
    menWomen: ['54', '46'],
    clients: '3224',
    autosLight: '33,69%',
    autosCommercial: '13,78%',
    autosCargo: '20,30%',
    autosSpecial: '28,43%',
    buses: '1,24%',
    equipment: '2,57%',
    faceImg: '/img/popupImg/Rostov-on-Don/face.png',
    bgImg: '/img/popupImg/Rostov-on-Don/bg.svg',
  },
  {
    id: 'Novorossiysk',
    name: 'Новороссийск',
  },
  {
    id: 'Samara',
    name: 'Самара',
    title: 'Поволжский филиал',
    cityName: 'г. Самара',
    manager: 'Каюков Захар Владимирович',
    position: 'Директор филиала',
    congratsText:
      '«От всей души поздравляю команду СберЛизинга с 30-летием! Желаю каждому сотруднику самореализации, желания расти вместе с компанией, получать только положительные эмоции от каждого прожитого дня, находить время для своих близких людей.Я счастлив работать в команде единомышленников! Процветания компании и каждому сотруднику!»',
    foundationYear: '2010',
    employeesNumber: '70',
    menWomen: ['40', '60'],
    clients: '2258',
    autosLight: '29,06%',
    autosCommercial: '12,06%',
    autosCargo: '18,31%',
    autosSpecial: '37,48%',
    buses: '0,62%',
    equipment: '2,48%',
    faceImg: '/img/popupImg/Samara/face.png',
    bgImg: '/img/popupImg/Samara/bg.svg',
  },
  {
    id: 'Yekaterinburg',
    name: 'Екатеринбург',
    title: 'Уральский филиал',
    cityName: 'г. Екатеринбург',
    manager: 'Вольф Антон Вадимович',
    position: 'Директор филиала',
    congratsText:
      '«Уважаемые партнёры и коллеги! Поздравляю вас с 30-летием компании! СберЛизинг видит своей миссией помогать клиентам достигать целей любого масштаба и обеспечивать удобный сервис и долгосрочное партнёрство. Наша команда благодрит клиентов за доверие!»',
    foundationYear: '2004',
    employeesNumber: '82',
    menWomen: ['48', '52'],
    clients: '2979',
    autosLight: '26,59%',
    autosCommercial: '15,13%',
    autosCargo: '28,18%',
    autosSpecial: '26,72%',
    buses: '1,55%',
    equipment: '2,27%',
    faceImg: '/img/popupImg/Yekaterinburg/face.png',
    bgImg: '/img/popupImg/Yekaterinburg/bg.svg',
  },
  {
    id: 'Arkhangelsk',
    name: 'Архангельск',
  },
  {
    id: 'Barnaul',
    name: 'Барнаул',
  },
  {
    id: 'Kurgan',
    name: 'Курган',
  },
  {
    id: 'Petrozavodsk',
    name: 'Петрозаводск',
  },
  {
    id: 'Cherepovets',
    name: 'Череповец',
  },
  {
    id: 'Veliky Novgorod',
    name: 'Великий Новгород',
  },
  {
    id: 'Pskov',
    name: 'Псков',
  },
  {
    id: 'Krasnodar',
    name: 'Краснодар',
  },
  {
    id: 'Stavropol',
    name: 'Ставрополь',
  },
  {
    id: 'Penza',
    name: 'Пенза',
  },
  {
    id: 'Orenburg',
    name: 'Оренбург',
  },
  {
    id: 'Omsk',
    name: 'Омск',
  },
  {
    id: 'Chelyabinsk',
    name: 'Челябинск',
  },
  {
    id: 'Belgorod',
    name: 'Белгород',
  },
  {
    id: 'Novokuznetsk',
    name: 'Новокузнецк',
  },
  {
    id: 'Chita',
    name: 'Чита',
  },
  {
    id: 'Ulan-Ude',
    name: 'Улан-Удэ',
  },
  {
    id: 'Bryansk',
    name: 'Брянск',
  },
  {
    id: 'Oryol',
    name: 'Орел',
  },
  {
    id: 'Smolensk',
    name: 'Смоленск',
  },
  {
    id: 'Blagoveshchensk',
    name: 'Благовещенск',
  },
  {
    id: 'Yakutsk',
    name: 'Якутск',
  },
  {
    id: 'Vladimir',
    name: 'Владимир',
  },
  {
    id: 'Ryazan',
    name: 'Рязань',
  },
  {
    id: 'Tyumen',
    name: 'Тюмень',
  },
  {
    id: 'Ufa',
    name: 'Уфа',
  },
  {
    id: 'Ulyanovsk',
    name: 'Ульяновск',
  },
  {
    id: 'Saransk',
    name: 'Саранск',
  },
  {
    id: 'Naberezhnye Chelny',
    name: 'Набережные Челны',
  },
  {
    id: 'Izhevsk',
    name: 'Ижевск',
  },
  {
    id: 'Kazan',
    name: 'Казань',
  },
  {
    id: 'Khabarovsk',
    name: 'Хабаровск',
  },
  {
    id: 'Yuzhno-Sakhalinsk',
    name: 'Южно-Сахалинск',
  },
  {
    id: 'Ivanovo',
    name: 'Иваново',
  },
  {
    id: 'Saratov',
    name: 'Саратов',
  },
  {
    id: 'Kirov',
    name: 'Киров',
  },
  {
    id: 'Syktyvkar',
    name: 'Сыктывкар',
  },
  {
    id: 'Cheboksary',
    name: 'Чебоксары',
  },
  {
    id: 'Kaliningrad',
    name: 'Калининград',
  },
  {
    id: 'Kaluga',
    name: 'Калуга',
  },
  {
    id: 'Tula',
    name: 'Тула',
  },
  {
    id: 'Kemerovo',
    name: 'Кемерово',
  },
  {
    id: 'Nizhnevartovsk',
    name: 'Нижневартовск',
  },
  {
    id: 'Surgut',
    name: 'Сургут',
  },
  {
    id: 'Lipetsk',
    name: 'Липецк',
  },
  {
    id: 'Tver',
    name: 'Тверь',
  },
  {
    id: 'Tolyatti',
    name: 'Тольятти',
  },
  {
    id: 'Tomsk',
    name: 'Томск',
  },
  {
    id: 'Volgodonsk',
    name: 'Волгодонск',
  },
  {
    id: 'Pyatigorsk',
    name: 'Пятигорск',
  },
  {
    id: 'Volgograd',
    name: 'Волгоград',
  },
  {
    id: 'Krasnoyarsk',
    name: 'Красноярск',
  },
  {
    id: 'Novy Urengoy',
    name: 'Новый Уренгой',
  },
  {
    id: 'Salekhard',
    name: 'Салехард',
  },
  {
    id: 'Perm',
    name: 'Пермь',
  },
  {
    id: 'Kursk',
    name: 'Курск',
  },
  {
    id: 'Tambov',
    name: 'Тамбов',
  },
  {
    id: 'Magadan',
    name: 'Магадан',
  },
  {
    id: 'Vologda',
    name: 'Вологда',
  },
  {
    id: 'Yaroslavl',
    name: 'Ярославль',
  },
  {
    id: 'Astrakhan',
    name: 'Астрахань',
  },
  {
    id: 'Moscow1',
    name: 'Москва',
    title: 'Московский филиал',
    cityName: 'г. Москва',
    manager: 'Алексеев Дмитрий Геннадьевич',
    position: 'Директор филиала',
    congratsText:
      '«Поздравляю с 30-летним юбилеем всех клиентов и сотрудников СберЛизинга. Пусть клиентам всегда будет с нами легко и комфортно —мы ежедневно делаем все от нас зависящее, чтобы именно так и было! А всей нашей большой и дружной команде лучшей лизинговой компании страны — здоровья, радости и удовольствия от жизни и работы. Вперед к новым рекордам!»',
    foundationYear: '2019',
    employeesNumber: '95',
    menWomen: ['60', '40'],
    clients: '2779',
    autosLight: '39,75%',
    autosCommercial: '18,24%',
    autosCargo: '25,16%',
    autosSpecial: '14,65%',
    buses: '0,66%',
    equipment: '1,54%',
    faceImg: '/img/popupImg/Moscow1/face.png',
    bgImg: '/img/popupImg/Moscow1/bg.svg',
  },
  {
    id: 'Moscow2',
    name: 'Москва',
    title: 'Среднерусский филиал',
    cityName: 'г. Москва',
    manager: 'Мудрова Ольга Владимировна',
    position: 'Директор филиала',
    congratsText:
      '«Поздравляю вас, коллеги, с юбилеем компании! Желаю всем нам бравого энтузиазма и высоких результатов, креативных идей и интересной работы, дружбы и взаимопонимания в коллективе, личного блага и счастливой жизни. Процветания СберЛизингу и отличных продаж!»',
    foundationYear: '2010',
    employeesNumber: '88',
    menWomen: ['40', '60'],
    clients: '2876',
    autosLight: '35,07%',
    autosCommercial: '20,07%',
    autosCargo: '22,31%',
    autosSpecial: '19,80%',
    buses: '1,07%',
    equipment: '1,68%',
    faceImg: '/img/popupImg/Moscow2/face.png',
    bgImg: '/img/popupImg/Moscow2/bg.svg',
  },
  {
    id: 'Saint Petersburg',
    name: 'Санкт-Петербург',
    title: 'Северо-Западный филиал',
    cityName: 'г. Санкт-Петербург',
    manager: 'Попова Оксана Васильевна',
    position: 'Директор филиала',
    congratsText:
      '«Поздравляю весь коллектив с Днём рождения компании! Самый ценный ресурс компании - это её сотрудники, именно они помогают нашим замечательным клиентам решать бизнес-задачи по обновлению основных средств. От всей души желаю ребятам здоровья, оптимизма, задора, профессионального роста, а самое главное — получать каждый день удовольствие от любимого дела! Нашим клиентам желаю процветания и расширения бизнеса!»',
    foundationYear: '2009',
    employeesNumber: '83',
    menWomen: ['50', '50'],
    clients: '2492',
    autosLight: '39,84%',
    autosCommercial: '17,72%',
    autosCargo: '21,29%',
    autosSpecial: '17,86%',
    buses: '1,49%',
    equipment: '1,80%',
    faceImg: '/img/popupImg/Saint_Petersburg/face.png',
    bgImg: '/img/popupImg/Saint_Petersburg/bg.svg',
  },
  {
    id: 'Nizhny Novgorod',
    name: 'Нижний Новгород',
    title: 'Волго-Вятский филиал',
    cityName: 'г. Нижний Новгород',
    manager: 'Тюрина Екатерина Сергеевна',
    position: 'Директор филиала',
    congratsText:
      '«Поздравляю с Днём рождения наш любимый СберЛизинг! Я желаю достижения всех наших амбициозных целей, лидерских позиций в рейтингах, сплоченной, целеустремленной команды и довольных, счастливых клиентов!»',
    foundationYear: '2002',
    employeesNumber: '82',
    menWomen: ['33', '67'],
    clients: '3023',
    autosLight: '31,60%',
    autosCommercial: '16,10%',
    autosCargo: '24,21%',
    autosSpecial: '24,50%',
    buses: '1,67%',
    equipment: '1,89%',
    faceImg: '/img/popupImg/Nizhny_Novgorod/face.png',
    bgImg: '/img/popupImg/Nizhny_Novgorod/bg.svg',
  },
  {
    id: 'Irkutsk',
    name: 'Иркутск',
    title: 'Байкальский филиал',
    cityName: 'г. Иркутск',
    manager: 'Митронин Анатолий Юрьевич',
    position: 'Директор филиала',
    congratsText:
      '«От имени коллектива Байкальского регионального филиала и от себя лично поздравляю всех сотрудников СберЛизинга с 30-летним юбилеем! Поздравляю не просто сотрудников, а команду профессионалов, способных справиться с любыми задачами! Хочется пожелать благополучия, полноты сил для достижения новых целей, уверенности в завтрашнем дне и надёжных партнеров!»',
    foundationYear: '2010',
    employeesNumber: '51',
    menWomen: ['38', '62'],
    clients: '2046',
    autosLight: '16,09%',
    autosCommercial: '7,01%',
    autosCargo: '46,86%',
    autosSpecial: '25,39%',
    buses: '0,60%',
    equipment: '2,23%',
    faceImg: '/img/popupImg/Irkutsk/face.png',
    bgImg: '/img/popupImg/Irkutsk/bg.svg',
  },
  {
    id: 'Novosibirsk',
    name: 'Новосибирск',
    title: 'Сибирский филиал',
    cityName: 'г. Новосибирск',
    manager: 'Миронов Антон Юрьевич',
    position: 'Директор филиала',
    congratsText:
      '«Дорогие клиенты и партнеры! Все эти 30-лет командой СберЛизинга растем и развиваемся вместе с Вами, радуемся вашим успехам, находим нестандартные решения, создаем новые программы и делимся своим опытом. Желаю чтобы все самые смелые проекты в бизнесе, идеи и даже мечты реализовывались и сбывались в партнерстве с нашей компанией! Спасибо за ваше доверие и сотрудничество».',
    foundationYear: '2008',
    employeesNumber: '101',
    menWomen: ['39', '61'],
    clients: '3976',
    autosLight: '29,41%',
    autosCommercial: '11,90%',
    autosCargo: '25,80%',
    autosSpecial: '27,44%',
    buses: '2,04%',
    equipment: '3,38%',
    faceImg: '/img/popupImg/Novosibirsk/face.png',
    bgImg: '/img/popupImg/Novosibirsk/bg.svg',
  },
];

export const ImagesInfo = [
  {
    name: 'i_1_t',
    position: [0.345, 0.5, -18.215],
    scale: 1.0,
    fadeInStartPosition: null,
  },
  {
    name: 'i_1_b',
    position: [0.01, -1.0, -20.58],
    scale: 1.0,
    fadeInStartPosition: null,
  },
  {
    name: 'i_2',
    position: [0.73, 0.0, -17.535],
    scale: 0.57,
    fadeInStartPosition: -17.5,
  },
  {
    name: 'i_3',
    position: [-0.76, 0.0, -16.6],
    scale: 1.4,
    fadeInStartPosition: -17.1,
  },
  {
    name: 'i_4',
    position: [0.3, 0.0, -13.945],
    scale: 0.6,
    fadeInStartPosition: -14,
  },
  {
    name: 'i_5_1',
    position: [-0.57, -1.0, -12.4],
    scale: 1.5,
    fadeInStartPosition: -11.8,
  },
  {
    name: 'i_5_2',
    position: [0.795, -1.0, -13.697],
    scale: 1.5,
    fadeInStartPosition: -11.8,
  },
  {
    name: 'i_5_3',
    position: [0.115, 1.0, -10.6],
    scale: 0.09,
    fadeInStartPosition: -11.8,
  },
  {
    name: 'i_5_4',
    position: [0.145, 1.0, -10.73],
    scale: 0.07,
    fadeInStartPosition: -11.8,
  },
  {
    name: 'i_6',
    position: [-0.2, 0.5, -9.795],
    scale: 1.2,
    fadeInStartPosition: -11,
  },
  {
    name: 'i_7_b',
    position: [-0.047, -1.0, -9.9],
    scale: 1.0,
    fadeInStartPosition: -9,
  },
  {
    name: 'i_7_t',
    position: [-0.047, 1.0, -7.1],
    scale: 1.0,
    fadeInStartPosition: -9,
  },
  {
    name: 'i_8_b',
    position: [-0.32, 0, -7.15],
    scale: 1.1,
    fadeInStartPosition: -7.5,
  },
  {
    name: 'i_8_t',
    position: [0.4, 0, -6.5],
    scale: 0.7,
    fadeInStartPosition: -6.9,
  },
  {
    name: 'i_9_b',
    position: [-0.75, 0, -4.52],
    scale: 1.8,
    fadeInStartPosition: -4.7,
  },
  {
    name: 'i_9_t',
    position: [0.65, 0, -3.65],
    scale: 2.0,
    fadeInStartPosition: -4.3,
  },
  {
    name: 'i_10',
    position: [-0.3, 0, -2.8],
    scale: 0.6,
    fadeInStartPosition: -2.8,
  },
  {
    name: 'i_11_b',
    position: [-0.5, 0, -1.46],
    scale: 1.4,
    fadeInStartPosition: -1.4,
  },
  {
    name: 'i_11_t',
    position: [0.21, 1, 0.67],
    scale: 0.965,
    fadeInStartPosition: -1.4,
  },
  {
    name: 'i_12',
    position: [0.67, 0, 0.92],
    scale: 1.8,
    fadeInStartPosition: 0.3,
  },
  {
    name: 'i_13',
    position: [-0.75, 0, 3.8],
    scale: 0.9,
    fadeInStartPosition: 3.5,
  },
  {
    name: 'i_14',
    position: [0.33, 0, 5.4],
    scale: 1.0,
    fadeInStartPosition: 5.5,
  },
  {
    name: 'i_15_1',
    position: [-0.4, 0, 6.9],
    scale: 0.45,
    fadeInStartPosition: 7,
  },
  {
    name: 'i_15_2_b',
    position: [-0.36, -1, 6.46],
    scale: 1.1,
    fadeInStartPosition: 7.7,
  },
  {
    name: 'i_15_2_t',
    position: [-0.36, 1, 9.26],
    scale: 1.1,
    fadeInStartPosition: 7.7,
  },
  {
    name: 'i_15_3',
    position: [-0.42, 0.2, 8.86],
    scale: 0.35,
    fadeInStartPosition: 8.3,
  },
  {
    name: 'i_15_4',
    position: [0.0, 0, 8.62],
    scale: 0.35,
    fadeInStartPosition: 8.7,
  },
  {
    name: 'i_16',
    position: [-0.08, -2, 7.74],
    scale: 2.6,
    fadeInStartPosition: 10,
  },
  {
    name: 'i_17',
    position: [-0.37, 1, 15.55],
    scale: 1.1,
    fadeInStartPosition: 14,
  },
  {
    name: 'i_18',
    position: [0.35, 0, 16.8],
    scale: 0.9,
    fadeInStartPosition: 17,
  },
  {
    name: 'salut',
    position: [0.7, 1, 18.6],
    scale: 0.9,
    fadeInStartPosition: 18,
  },
];

export const BlockWithTextInfo = [
  {
    positionZ: -18.3,
    element: document.querySelector('.webgl-html-text-wrapper_0'),
  },
  {
    positionZ: -16.8,
    element: document.querySelector('.webgl-html-text-wrapper_1'),
  },
  {
    positionZ: -15.3,
    element: document.querySelector('.webgl-html-text-wrapper_2'),
  },
  {
    positionZ: -13.3,
    element: document.querySelector('.webgl-html-text-wrapper_3'),
  },
  {
    positionZ: -10.9,
    element: document.querySelector('.webgl-html-text-wrapper_4'),
  },
  {
    positionZ: -8.5,
    element: document.querySelector('.webgl-html-text-wrapper_5'),
  },
  {
    positionZ: -6.8,
    element: document.querySelector('.webgl-html-text-wrapper_6'),
  },
  {
    positionZ: -6.6,
    element: document.querySelector('.webgl-html-text-wrapper_7'),
  },
  {
    positionZ: -4.75,
    element: document.querySelector('.webgl-html-text-wrapper_8'),
  },
  {
    positionZ: -2.45,
    element: document.querySelector('.webgl-html-text-wrapper_9'),
  },
  {
    positionZ: -0.85,
    element: document.querySelector('.webgl-html-text-wrapper_10'),
  },
  {
    positionZ: 1.3,
    element: document.querySelector('.webgl-html-text-wrapper_11'),
  },
  {
    positionZ: 4.7,
    element: document.querySelector('.webgl-html-text-wrapper_12'),
  },
  {
    positionZ: 7.4,
    element: document.querySelector('.webgl-html-text-wrapper_13'),
  },
  {
    positionZ: 9.2,
    element: document.querySelector('.webgl-html-text-wrapper_14'),
  },
  {
    positionZ: 10.7,
    element: document.querySelector('.webgl-html-text-wrapper_15'),
  },
  {
    positionZ: 14.8,
    element: document.querySelector('.webgl-html-text-wrapper_16'),
  },
  {
    positionZ: 16.8,
    element: document.querySelector('.webgl-html-text-wrapper_17'),
  },
];
